### ISSUE TITLE
Failure to build with GCC 7

### ISSUE THREAD

**Issue by satta** [marbl/Mash#47]
The released Mash version 1.1.1 fails to build with GCC 7:
```
$ ./configure --with-capnp=/usr
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for capnp... yes
checking capnp/common.h usability... yes
checking capnp/common.h presence... yes
checking for capnp/common.h... yes
checking gsl/gsl_cdf.h usability... yes
checking gsl/gsl_cdf.h presence... yes
checking for gsl/gsl_cdf.h... yes
configure: creating ./config.status
config.status: creating Makefile
$ CXX=g++-7 make -j3
cd src/mash/capnp;export PATH=/usr/bin/:/usr/local/opt/ccache/libexec:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/vagrant/bin:/home/vagrant/uni/gt/bin:/home/vagrant/uni/research/bin:/home/vagrant/uni/lehre/repo/bin;capnp compile -I /usr/include -oc++ MinHash.capnp
cd src/mash/capnp;export PATH=/usr/bin/:/usr/local/opt/ccache/libexec:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/vagrant/bin:/home/vagrant/uni/gt/bin:/home/vagrant/uni/research/bin:/home/vagrant/uni/lehre/repo/bin;capnp compile -I /usr/include -oc++ MinHash.capnp
cc -include src/mash/memcpyLink.h -c -o src/mash/memcpyWrap.o src/mash/memcpyWrap.c
g++-7 -c -O3 -std=c++11 -Isrc -I/usr/include -I /usr/local//include -include src/mash/memcpyLink.h -Wl,--wrap=memcpy  -o src/mash/capnp/MinHash.capnp.o src/mash/capnp/MinHash.capnp.c++
In file included from /usr/include/capnp/generated-header-support.h:31:0,
                 from src/mash/capnp/MinHash.capnp.h:7,
                 from src/mash/capnp/MinHash.capnp.c++:4:
/usr/include/capnp/layout.h:129:65: error: could not convert template argument ‘b’ from ‘bool’ to ‘capnp::Kind’
 template <typename T, bool b> struct ElementSizeForType<List<T, b>> {
                                                                 ^
/usr/include/capnp/layout.h:129:66: error: template argument 1 is invalid
 template <typename T, bool b> struct ElementSizeForType<List<T, b>> {
                                                                  ^~
g++-7 -c -O3 -std=c++11 -Isrc -I/usr/include -I /usr/local//include -include src/mash/memcpyLink.h -Wl,--wrap=memcpy  -o src/mash/Command.o src/mash/Command.cpp
g++-7 -c -O3 -std=c++11 -Isrc -I/usr/include -I /usr/local//include -include src/mash/memcpyLink.h -Wl,--wrap=memcpy  -o src/mash/CommandBounds.o src/mash/CommandBounds.cpp
Makefile:50: recipe for target 'src/mash/capnp/MinHash.capnp.o' failed
make: *** [src/mash/capnp/MinHash.capnp.o] Error 1
make: *** Waiting for unfinished jobs....
```
This is on Debian stretch, x86_64.

**Comment by ondovb** [comment]
Looks like Cap'n Proto generated code might not be compatible with new syntax rules in cutting-edge compiler versions. I've forwarded this on to the Cap'n Proto mailing list, but for now you should be able to either compile with an older gcc (4.8-6) or run the binaries.

**Comment by satta** [comment]
Thanks for your quick action. I'm the maintainer for Mash in Debian, which is slowly moving towards a newer default compiler (GCC 7). So to be able to build Mash in the (not too near) future I was looking to get this addressed. Since binaries in Debian must be autobuilt from source the official binaries are not an option for distribution.
I'll be looking forward to what the Cap'n Proto team have to say. Many thanks again!

**Comment by ondovb** [comment]
Apparently this is already fixed in Cap'n Proto master (https://github.com/sandstorm-io/capnproto), so cloning from that should also fix this until the changes make it into an official Cap'n Proto release.
